'\" t
.\"     Title: rzscontrol
.\"    Author: Nitin Gupta <ngupta@vflare.org>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/19/2010
.\"    Manual:  
.\"    Source:    
.\"  Language: English
.\"
.TH "RZSCONTROL" "1" "05/19/2010" "" ""
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rzscontrol \- control ramzswap devices
.SH "SYNOPSIS"
.HP \w'\fBrzscontrol\fR\ 'u
\fBrzscontrol\fR {ramzswap\ device} [\-d|\-\-disksize_kb=<value>] [\-i|\-\-init] [\-r|\-\-reset] [\-s|\-\-stats] [\-v|\-\-verbose] [\-h|\-\-help]
.SH "DESCRIPTION"
.PP
The ramzswap kernel module creates multiple ramzswap devices, equal to num_devices parameter\&. With rzscontrol, you can control each of these devices\&.
.PP
This is how you use a ramzswap device (/dev/ramzswapX):
.PP
\- Set [disksize] parameter (see OPTIONS and EXAMPLES)\&.
.PP
\- Issue init once these parameters are set: rzscontrol /dev/ramzswapX \-\-init\&.
.PP
\- swapon /dev/ramzswapX (where X is ramzswap device id: 0, 1, 2\&.\&.\&. num_devices\-1)\&.
.PP
\- When you are done with this swap: swapoff /dev/ramzswapX\&. NOTE: swapoff will not free any compressed pages\&.
.PP
\- After swapoff, issue reset: rzscontrol /dev/ramzswapX \-\-reset\&. This will free all metadata and compressed pages\&.
.SH "OPTIONS"
.PP
\fB\-d, \-\-disksize_kb\fR
.RS 4
Specify ramzswap disk size (in KB)\&. This is the limit on number of (uncompressed) pages that can be stored in this device\&. Default: 25% of RAM
.RE
.PP
\fB\-i, \-\-init\fR
.RS 4
Initialize given ramzswap device\&. It causes allocation of metadata for given ramzswap device and makes it ready to receive swap requests\&. Use
\fBswapon\fR(8)
to start using this device as swap\&.
.RE
.PP
\fB\-r, \-\-reset\fR
.RS 4
Resets given ramzswap device\&. It causes deallocation of metadata and any compressed pages for given ramzswap device\&. If the device is currently active, use
\fBswapoff\fR(8)
before issuing reset (otherwise \-EBUSY error is returned)\&.
.RE
.PP
\fB\-s, \-\-stats\fR
.RS 4
Show stats for given ramzswap device\&. If the ramzswap kernel module was compiled without STATS support, then most of the stats will be shown as 0\&.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Show verbose output from rzscontrol\&.
.RE
.PP
\fB\-h, \-\-help\fR
.RS 4
Shows usage information and some examples\&.
.RE
.SH "EXAMPLES"
.PP
Following shows a typical sequence of steps for using ramzswap\&. Initialization can be done with many variations of configuration parameters as shown below\&.
.PP
Load Module:
.sp
.if n \{\
.RS 4
.\}
.nf
    insmod ramzswap\&.ko num_devices=4 # creates 4 uninitialized devices: /dev/ramzswap{0,1,2,3}
    
.fi
.if n \{\
.RE
.\}
.PP
Initialize:
.sp
.if n \{\
.RS 4
.\}
.nf
    rzscontrol /dev/ramzswap0 \-\-init # uses default value of disksize_kb
    rzscontrol /dev/ramzswap1 \-\-disksize_kb=10240 \-\-init
    
.fi
.if n \{\
.RE
.\}
.PP
Activate:
.sp
.if n \{\
.RS 4
.\}
.nf
    swapon /dev/ramzswap1 # or any other initialized ramzswap device
    
.fi
.if n \{\
.RE
.\}
.PP
Stats:
.sp
.if n \{\
.RS 4
.\}
.nf
    rzscontrol /dev/ramzswap1 \-\-stats
    
.fi
.if n \{\
.RE
.\}
.PP
Deactivate:
.sp
.if n \{\
.RS 4
.\}
.nf
    swapoff /dev/ramzswap1
    
.fi
.if n \{\
.RE
.\}
.PP
Reset:
.sp
.if n \{\
.RS 4
.\}
.nf
    rzscontrol /dev/ramzswap1 \-\-reset
    
.fi
.if n \{\
.RE
.\}
.PP
Unload Module:
.sp
.if n \{\
.RS 4
.\}
.nf
    rmmod ramzswap\&.ko
    
.fi
.if n \{\
.RE
.\}
.PP
NOTE: ramzswap parameters cannot be changed once the device is initialized\&. It has to be reset before new parameters can be used\&.
.SH "SEE ALSO"
.PP

\fBmkswap\fR(8),
\fBswapon\fR(8),
\fBswapoff\fR(8)
.SH "AUTHOR"
.PP
\fBNitin Gupta\fR <\&ngupta@vflare\&.org\&>
.RS 4
Developer
.RE
